### ISSUE TITLE
Encoders required to have a text input 

### ISSUE THREAD

**Issue by filliptm** [Extraltodeus/Vector_Sculptor_ComfyUI#1]
You should make the nodes useable without needed text, just for the sake of it not erroring out

**Comment by Extraltodeus** [comment]
But it can not work without text as it does not change the end and start if sequence tokens. Which populates empty text conditionings.

Quick edit tho: I realized what you actually meant. I'll skip the loop if the text is empty.

**Comment by Extraltodeus** [comment]
Fixed it! Thank you for noticing :D
