### ISSUE TITLE
awesome work - wanted some more info

### ISSUE THREAD

**Issue by jags111** [Extraltodeus/Vector_Sculptor_ComfyUI#2]
Can you add some more examples or links to examples with workflows using these nodes as discussed for slerp and condition nodes as these can be very helpful. 
further when you try and load your samples as shared in repo some 4 nodes show as red. what nodes are these (1) PIL to image (2) ImagetoPIL (3) image concatenate (4) Write on PIL image.. really could not find any reference on same as wanted to check how these are done and how the variations on strength of these image obtained in the samples shared. Also the grid PNG (x-y plots) to compare same.

**Comment by Extraltodeus** [comment]
> Can you add some more examples or links to examples with workflows using these nodes as discussed for slerp and condition nodes as these can be very helpful.

Well I made these, tested a bit and added them. So I don't have much more generated examples than what you could by experimenting around.

> further when you try and load your samples as shared in repo some 4 nodes show as red. what nodes are these (1) PIL to image (2) ImagetoPIL (3) image concatenate (4) Write on PIL image.. really could not find any reference on same as wanted to check how these are done and how the variations on strength of these image obtained in the samples shared. Also the grid PNG (x-y plots) to compare same.

Sure!

I uploaded them. You can find all of them [here](https://github.com/Extraltodeus/CustomComfyUINodes_random_stash/blob/main/image_PIL_text.py), [here](https://github.com/Extraltodeus/CustomComfyUINodes_random_stash/blob/main/image_zoom.py) and [here](https://github.com/Extraltodeus/CustomComfyUINodes_random_stash/blob/main/image_to_PIL.py)
