### ISSUE TITLE
Results - This was a trip!

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Extraltodeus/Vector_Sculptor_ComfyUI#4]
Not an issue, I just wanted to share my results.

Using this produces weird result.
Sometimes good, sometimes bad, sometimes (most times), weird!

I decided to run it through a bunch of random prompts, and generate one with and one without for each one.

Here's a link to a zip file with 882 pairs of images using this.

[https://huggingface.co/datasets/mnemic/VectorSculptorResults/blob/main/README.md](https://huggingface.co/datasets/mnemic/VectorSculptorResults/blob/main/README.md)

Without:
![2024-03-28-14_18_28 - basic 001](https://github.com/Extraltodeus/Vector_Sculptor_ComfyUI/assets/60541708/492203ab-4d24-4830-9ad7-0969745cf963)

With:
![2024-03-28-14_18_28 - sculpted 001](https://github.com/Extraltodeus/Vector_Sculptor_ComfyUI/assets/60541708/ef1addda-c3a5-4593-972c-1b7ad739a8f6)

CHAOS!

**Comment by Extraltodeus** [comment]
lol thank you! Yes indeed sometimes dosing the settings can make things weirds. Thank you for sharing your tests!!! :D

**Comment by Extraltodeus** [comment]
If you don't mind I added them to the readme!

**Comment by MNeMoNiCuZ** [comment]
Go for it! Feel free to cherry pick from the shared images :)

**Comment by Extraltodeus** [comment]
Done :D
